### ISSUE TITLE
`test_no_replication_across_clusters` unstable

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mysql-k8s-operator#202]
Replication test `test_no_replication_across_clusters` unstable: failed 4 times in a row, blocking release CI: https://github.com/canonical/mysql-k8s-operator/actions/runs/4667631230/jobs/8265947160

Marked as unstable in #201

**Comment by taurus-forever** [comment]
Just for the history: [those](https://github.com/canonical/mysql-k8s-operator/pull/199) PR merged and released after re-triggering.  

I think, I know the reason of instability for those test:
We start 2 DB clusters there: mysql and "anothermysql" each of them eats 50% RAM, causing OOM which triggers issues due to know Workload container restart and lack of pebble socket connection:
``
  File "/var/lib/juju/agents/unit-another-mysql-1/charm/venv/ops/pebble.py", line 252, in connect
    self.sock.connect(self.socket_path)
FileNotFoundError: [Errno 2] No such file or directory
``

See: https://github.com/canonical/operator/issues/844#issuecomment-1488268566

And the fix is planned here: https://github.com/canonical/mysql-k8s-operator/issues/192 we must lock (with contsraints) RAM usage of each mysql and anothermysql to 1GB and not 50% RAM.

**Comment by taurus-forever** [comment]
I am really curious, what is using ~6-8G there during the tests?
We are not importing any data into database in those tests, so both DBs are empty. Sure, `innodb_buffer_pool_size=50%` RAM, but MySQL should not `use` all of them, it is a maximum allowed value.

Any ideas why MySQL eats 6 GB RAM? Also I can't explain why RAM usage is not decreased on workload charm restart (gap on the picture?).
@carlcsaposs-canonical @delgod
